[[redirects]]
  from = "/api/*"
  to = "https://vantum-prod.herokuapp.com/api/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "https://app.vantum.com.br/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://agronatura.vantum.com.br/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://reference.vantum.com.br/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://3dgeo.vantum.com.br/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://app.agronatura-ca.com.br/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://beta.vantum.com.br/*"
  to = "/index.html"
  status = 200